name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    release:
        types: [ published ]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.6.10"

            - name: Set up Pyhon
              uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"

            - name: Install llamore
              run: uv sync --all-extras

            - name: Run tests
              run: uv run pytest tests

    release:
        runs-on: ubuntu-latest
        # if: {{ github.event_name == 'release' }}
        needs: tests
        environment: 
            name: pypi
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.6.10"

            - name: Build package
              run: uv build

            - name: Smoke test (wheel)
              run: uv run --isolated --no-project -p 3.10 --with dist/*whl -- python -c "import llamore"

            - name: Smoke test (source)
              run: uv run --isolated --no-project -p 3.10 --with dist/*tar.gz -- python -c "import llamore"

            - name: Publish package
              run: uv publish --index testpypi --trusted-publishing always